spring:
  profiles:
        active:
            - dog
            - EN
            - dev
  banner:
    location: banner.txt
    banner-mode: console
sfgdi:
      username: YmlUserName
      password: YmlPassword
      jdbcurl: YmlUrl

---

spring:
  profiles: prod
sfgdi:
  username: YmlProdUserName
  password: YmlProdPassword
  jdbcurl: YmlProdUrl
