spring:
  profiles:
        active:
            - dog
            - ES
            - dev
            - map
  banner:
    location: banner.txt
    banner-mode: console
  messages:
    basename: messages/messages
sfgdi:
      username: YmlUserName
      password: YmlPassword
      jdbcurl: YmlUrl

---

spring:
  profiles: prod
sfgdi:
  username: YmlProdUserName
  password: YmlProdPassword
  jdbcurl: YmlProdUrl
